camel.main.modeline=true
camel.jbang.compileWorkDir=.camel-jbang/compile
camel.jbang.health=false
camel.jbang.metrics=false
camel.jbang.console=false
camel.jbang.verbose=false
camel.jbang.camel-version=4.17.0-SNAPSHOT
camel.jbang.springBootVersion=3.5.9
camel.jbang.quarkusVersion=3.30.6
camel.jbang.quarkusGroupId=io.quarkus.platform
camel.jbang.quarkusArtifactId=quarkus-bom
camel.jbang.kameletsVersion=4.17.0
camel.main.name=main-route
camel.main.routesIncludePattern=file\:main-route.camel.yaml
camel.component.properties.location=file\:forage-agent-factory.properties
camel.jbang.dependencies=mvn\:io.kaoto.forage\:forage-agent\:1.0-SNAPSHOT,mvn\:io.quarkiverse.langchain4j\:quarkus-langchain4j-ollama\:1.2.2,mvn\:io.kaoto.forage\:forage-model-quarkus\:1.0-SNAPSHOT,camel\:cli-connector
dependency=mvn\:org.apache.camel\:camel-cli-connector\:4.17.0-SNAPSHOT
dependency=mvn\:io.kaoto.forage\:forage-agent\:1.0-SNAPSHOT
dependency=mvn\:io.quarkiverse.langchain4j\:quarkus-langchain4j-ollama\:1.2.2
dependency=mvn\:io.kaoto.forage\:forage-model-quarkus\:1.0-SNAPSHOT
dependency=mvn\:org.apache.camel\:camel-kamelet\:4.17.0-SNAPSHOT
dependency=mvn\:org.apache.camel.kamelets\:camel-kamelets\:4.17.0
dependency=mvn\:org.apache.camel\:camel-yaml-dsl\:4.17.0-SNAPSHOT
dependency=mvn\:org.apache.camel\:camel-core-languages\:4.17.0-SNAPSHOT
dependency=mvn\:org.apache.camel\:camel-langchain4j-agent\:4.17.0-SNAPSHOT
dependency=mvn\:org.apache.camel\:camel-platform-http\:4.17.0-SNAPSHOT
camel.server.port=8080
dependency=mvn\:org.apache.camel\:camel-jackson\:4.17.0-SNAPSHOT
